#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly = TRUE); sp <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]); lab <- dirname(dirname(normalizePath(sp, mustWork = TRUE))); base <- file.path(lab, "work")
if (length(args) == 1L && args[[1]] %in% c("--help", "-h")) { cat("Usage: Rscript checks/check_lab4.R [--cumulative PATH]\nDefault checks this lab's work/; --cumulative checks an exported lab-04 payload.\n"); quit(status = 0L) }
if (length(args) == 2L && args[1] %in% c("--base", "--cumulative")) { base <- normalizePath(args[2], mustWork = FALSE) } else if (length(args) == 1L) { base <- normalizePath(args[1], mustWork = FALSE) } else if (length(args)) stop("usage: Rscript checks/check_lab4.R [--cumulative PATH]", call. = FALSE)
fixture <- file.path(lab, "fixture", "release"); read <- function(p) read.csv(p, stringsAsFactors = FALSE, na.strings = c("", "NA"), check.names = FALSE)
expected <- c(household_wave.csv = "3c5eec09c11c4f13391f2366366938082e3b31bd6f473296cdce64a292a5243a", person_static.csv = "518f9220146b5e6afddd80cbdd61f57b3522a6f06e54533cc3c0e77cb581596b", person_wave.csv = "a6fba10e259a304ef7ac3f013c378966e8f379b5c76153efbd71fb8c95c7f8af", questionnaire.csv = "48bf1693afa4eeb11c0053fe275a95c022434d9006d98b3cbd97e098a067c8e4", release_manifest.csv = "746171580a4493bb9edc3265d5a02ae0579652a3ece16a1533ccff6768b05a31", response.csv = "67e45b4388808e0b014c84d55a30eb042f23180c131ad765146d56c5da8408af", schema.csv = "7cc4c3cf407494ce80806b71ebcc7e6669fb978d187fedc5590befd5965dd393")
if (!requireNamespace("digest", quietly = TRUE)) stop("digest package is required", call. = FALSE)
actual <- vapply(names(expected), function(n) if (file.exists(file.path(fixture, n))) digest::digest(file = file.path(fixture, n), algo = "sha256", serialize = FALSE) else "MISSING", character(1))
if (!identical(unname(actual), unname(expected))) { cat("FAIL immutable fixture changed\n"); quit(status = 1L) }
pw <- read(file.path(fixture, "person_wave.csv")); key <- paste(pw$pid, pw$wave, sep = "::"); precondition <- nrow(pw) == 513L && sum(pw$income_imp[pw$pid == "P000040" & pw$wave == 2019L]) == 0L
if (!precondition) { cat("FAIL intended fixture precondition changed\n"); quit(status = 1L) }
cat("PASS precondition: fixture fails only income_consistency at P000040::2019\n")
needed <- c(file.path(base, "release", "person_wave.csv"), file.path(base, "outputs", "income-summary.csv"), file.path(base, "LOOP.md"), file.path(base, "GOALS.md"), file.path(base, "WORKLOG.md"), file.path(base, "code", "repair_release.R"), file.path(base, "code", "summarize_income.R"), file.path(base, "DECISIONS.md"), file.path(base, "HANDOFF.md"), file.path(base, "placement.md"), file.path(base, "logs", "attempt-1.txt"))
if (!all(file.exists(needed))) { cat("FAIL incomplete: repaired release, summary, loop log, WORKLOG, and handoff are required\n"); quit(status = 1L) }
run <- system2("Rscript", c(file.path(lab, "checks", "check_release.R"), "--base", base), stdout = TRUE, stderr = TRUE); code <- attr(run, "status"); if (!is.null(code) && code != 0L) { cat(paste(run, collapse = "\n"), "\n", sep = ""); quit(status = 1L) }
attempts <- list.files(file.path(base, "logs"), pattern = "^attempt-[0-9]+\\.txt$", full.names = TRUE); nums <- sort(as.integer(sub("^attempt-([0-9]+)\\.txt$", "\\1", basename(attempts))))
if (length(nums) < 1L || length(nums) > 2L || !identical(nums, seq_len(max(nums))) || file.exists(file.path(base, "logs", "attempt-3.txt"))) { cat("FAIL bounded loop must contain sequential attempt 1 or attempts 1-2, never attempt 3\n"); quit(status = 1L) }
for (p in attempts) { txt <- paste(readLines(p, warn = FALSE), collapse = "\n"); if (!grepl("generated_by=tools/run_attempt.sh", txt, fixed = TRUE) || !grepl("check_command=Rscript checks/check_release.R", txt, fixed = TRUE) || !grepl("diagnosis=", txt, fixed = TRUE) || !grepl("action=", txt, fixed = TRUE) || !grepl("result=", txt, fixed = TRUE)) { cat("FAIL attempt log is not generated evidence\n"); quit(status = 1L) } }
last <- paste(readLines(attempts[[which.max(nums)]], warn = FALSE), collapse = "\n"); if (!grepl("check_exit=0", last, fixed = TRUE) || !grepl("result=PASS", last, fixed = TRUE)) { cat("FAIL final bounded attempt did not pass\n"); quit(status = 1L) }
loop <- tolower(paste(readLines(file.path(base, "LOOP.md"), warn = FALSE), collapse = "\n")); if (!grepl("at most 2", loop, fixed = TRUE) || !grepl("human review", loop, fixed = TRUE) || grepl("attempt 3", loop, fixed = TRUE) == FALSE) { cat("FAIL LOOP.md lacks the two-attempt budget and stop rule\n"); quit(status = 1L) }
for (name in c("GOALS.md", "DECISIONS.md", "HANDOFF.md", "placement.md", "WORKLOG.md")) { txt <- tolower(paste(readLines(file.path(base, name), warn = FALSE), collapse = "\n")); if (nchar(txt) < 80L || grepl("not started|\\[write|\\[todo|\\[fill", txt)) { cat("FAIL placeholder or empty note: ", name, "\n", sep = ""); quit(status = 1L) } }
dec <- tolower(paste(readLines(file.path(base, "DECISIONS.md"), warn = FALSE), collapse = "\n")); if (!all(vapply(c("decision", "evidence", "alternatives", "rationale", "manifest"), grepl, logical(1), x = dec, fixed = TRUE))) { cat("FAIL decisions lack placement evidence and alternatives\n"); quit(status = 1L) }
place <- tolower(paste(readLines(file.path(base, "placement.md"), warn = FALSE), collapse = "\n")); if (!grepl("deterministic", place, fixed = TRUE) || !grepl("evidence", place, fixed = TRUE) || !grepl("classification", place, fixed = TRUE)) { cat("FAIL placement classification lacks evidence\n"); quit(status = 1L) }
worklog <- tolower(paste(readLines(file.path(base, "WORKLOG.md"), warn = FALSE), collapse = "\n")); if (!all(vapply(c("action", "evidence", "next step"), grepl, logical(1), x = worklog, fixed = TRUE))) { cat("FAIL WORKLOG lacks action/evidence/next-step records\n"); quit(status = 1L) }
hand <- tolower(paste(readLines(file.path(base, "HANDOFF.md"), warn = FALSE), collapse = "\n")); if (!all(vapply(c("source", "current state", "changed files", "last checker", "next action", "uncertainty", "stop", "human review"), grepl, logical(1), x = hand, fixed = TRUE))) { cat("FAIL handoff lacks fresh-context state, next action, uncertainty, stop, or human review\n"); quit(status = 1L) }
if (!grepl("last checker/result:[^\\n]*pass", hand) || !grepl("next action:[^\\n]*(human review|stop)", hand) || grepl("will report pass|run (bash )?tools/run_attempt.sh 1|run attempt 1|pending", hand)) { cat("FAIL handoff is stale: after a passing attempt it must record PASS and human-review/stop as the next action\n"); quit(status = 1L) }
cat("PASS lab 4: imputation flag, release manifest, income summary, bounded loop, logs, and handoff verified\n")
